version: '3.8'

services:
  abito-dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rredfearn32
    networks:
      - abito
networks:
  abito: